# data types in ansible

- name: data types
  hosts: local
  connection: local
  vars:
    PROGRAM: "devops with aws"
    duration: 140
    IS_LIVE: true
    DETAILS:
      months: 4
      trainer: siva